import type { Metadata } from "next";
import "./globals.css";
import NextAuthWrapper from "./lib/next.auth.wrapper";
import { Toaster } from "react-hot-toast";
import TokenCheck from "./lib/token.check";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body className={` antialiased font-popins`}>
        <NextAuthWrapper>
          <TokenCheck>{children}</TokenCheck>
        </NextAuthWrapper>
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
